/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Vista;

import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Controlador.AgendaController;
import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Examen;
import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Materia;
import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Tarea;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author and_j
 */
public class AgendaView extends JFrame {

    private AgendaController controller;

    public AgendaView(AgendaController controller) {
        this.controller = controller;
        setTitle("Agenda Estudiantil ESPOCH");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();

    }

    public void initComponents() {
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(5, 1, 10, 10));

        JButton btnMateria = new JButton("Agregar Materia");
        JButton btnTarea = new JButton("Agregar Tarea");
        JButton btnExamen = new JButton("Agregar Examen");
        JButton btnResumen = new JButton("Ver Resumen");

        btnMateria.addActionListener(e -> mostrarFormularioMateria());
        btnTarea.addActionListener(e -> mostrarFormularioTarea());
        btnExamen.addActionListener(e -> mostrarFormularioExamen());
        btnResumen.addActionListener(e -> mostrarResumen());

        panel.add(btnMateria);
        panel.add(btnTarea);
        panel.add(btnExamen);
        panel.add(btnResumen);

        add(panel);
    }

    public void mostrarFormularioMateria() {
        String nombre = JOptionPane.showInputDialog("Nombre materia:");
        String docente = JOptionPane.showInputDialog("Docente:");
        String horario = JOptionPane.showInputDialog("Horario:");
        String aula = JOptionPane.showInputDialog("Aula:");
        controller.agregarMateria(new Materia(nombre, docente, horario, aula));
    }

    public void mostrarFormularioTarea() {
        String descripcion = JOptionPane.showInputDialog("Descripción de tarea:");
        String fecha = JOptionPane.showInputDialog("Fecha:");
        controller.agregarTarea(new Tarea(descripcion, fecha));
    }

    public void mostrarFormularioExamen() {
        String materia = JOptionPane.showInputDialog("Materia del examen:");
        String fecha = JOptionPane.showInputDialog("Fecha del examen:");
        String tema = JOptionPane.showInputDialog("Tema:");
        controller.agregarExamen(new Examen(materia, fecha, tema));
    }

    public void mostrarResumen() {
        JTextArea textArea = new JTextArea(controller.listarResumen());
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(500, 300));
        JOptionPane.showMessageDialog(this, scrollPane, "Resumen General", JOptionPane.INFORMATION_MESSAGE);
    }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
