package ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Vista;

import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Controlador.AgendaController;

/**
 *
 * @author and_j
 */
public class NewJFrameMetas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameMetas
     */
    private AgendaController controlador;

    public NewJFrameMetas(AgendaController controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcionMeta = new javax.swing.JTextField();
        txtFechaMeta = new javax.swing.JTextField();
        radiobtnSiMeta = new javax.swing.JRadioButton();
        radiobtnNoMeta = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiarMetas = new javax.swing.JButton();
        btnGuardarMetas = new javax.swing.JButton();
        btnSalirMetas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("MiVidaEspoch");

        jLabel2.setText("Descripción:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Completado");

        txtDescripcionMeta.setText("ejem,Estudiar Ingles present perfect");
        txtDescripcionMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionMetaActionPerformed(evt);
            }
        });

        txtFechaMeta.setText("ejem,Martes,Hoy,Mañana");
        txtFechaMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaMetaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtnSiMeta);
        radiobtnSiMeta.setText("SI");
        radiobtnSiMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnSiMetaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtnNoMeta);
        radiobtnNoMeta.setText("No");

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Registro De Metas");

        btnLimpiarMetas.setText("Limpiar");
        btnLimpiarMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMetasActionPerformed(evt);
            }
        });

        btnGuardarMetas.setText("Guardar");

        btnSalirMetas.setText("Salir");
        btnSalirMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radiobtnSiMeta)
                                .addGap(26, 26, 26)
                                .addComponent(radiobtnNoMeta))
                            .addComponent(txtDescripcionMeta, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtFechaMeta))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalirMetas)
                    .addComponent(btnGuardarMetas)
                    .addComponent(btnLimpiarMetas))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radiobtnSiMeta)
                    .addComponent(radiobtnNoMeta))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarMetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarMetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirMetas)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtnSiMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnSiMetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnSiMetaActionPerformed

    private void txtFechaMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaMetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaMetaActionPerformed

    private void txtDescripcionMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionMetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionMetaActionPerformed

    private void btnSalirMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMetasActionPerformed

        new PrincipalView(controlador).setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnSalirMetasActionPerformed

    private void btnLimpiarMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMetasActionPerformed
        txtDescripcionMeta.setText("");
        txtFechaMeta.setText("");
        radiobtnNoMeta.setText("");
        radiobtnSiMeta.setText("");
    }//GEN-LAST:event_btnLimpiarMetasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMetas;
    private javax.swing.JButton btnLimpiarMetas;
    private javax.swing.JButton btnSalirMetas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radiobtnNoMeta;
    private javax.swing.JRadioButton radiobtnSiMeta;
    private javax.swing.JTextField txtDescripcionMeta;
    private javax.swing.JTextField txtFechaMeta;
    // End of variables declaration//GEN-END:variables

}
