package ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Vista;

import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Controlador.AgendaController;
import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Materia;
import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Meta;
import javax.swing.JOptionPane;

/**
 *
 * @author and_j
 */
public class NewJFrameMaterias extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameMaterias
     */
    private AgendaController controlador;

    public NewJFrameMaterias(AgendaController controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreDelDocente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxThora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiaHorario = new javax.swing.JTextField();
        btnLimpiarmateria = new javax.swing.JButton();
        btnGuardarMateria = new javax.swing.JButton();
        btnSalirMateria = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("MiVidaEspoch");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Registro de Materias");

        txtNombreMateria.setText("ejem,Calculo1");

        jLabel3.setText("Nombre de la Materia:");

        jLabel4.setText("Nombre del Docente:");

        txtNombreDelDocente.setText("ejem,Ing Mishell");
        txtNombreDelDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDelDocenteActionPerformed(evt);
            }
        });

        jLabel5.setText("Horas:");

        TxThora.setText("ejem,tres a cinco");
        TxThora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxThoraActionPerformed(evt);
            }
        });

        jLabel6.setText("Dia:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Horario");

        txtDiaHorario.setText("ejem,Lunes");
        txtDiaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaHorarioActionPerformed(evt);
            }
        });

        btnLimpiarmateria.setText("Limpiar");
        btnLimpiarmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarmateriaActionPerformed(evt);
            }
        });

        btnGuardarMateria.setText("Guardar");
        btnGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMateriaActionPerformed(evt);
            }
        });

        btnSalirMateria.setText("Salir");
        btnSalirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMateriaActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxThora)
                                            .addComponent(txtDiaHorario)
                                            .addComponent(txtNombreDelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLimpiarmateria, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSalirMateria)
                                            .addComponent(btnGuardarMateria)))))
                            .addComponent(jLabel7))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreDelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxThora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLimpiarmateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirMateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDelDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDelDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDelDocenteActionPerformed

    private void TxThoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxThoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxThoraActionPerformed

    private void txtDiaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaHorarioActionPerformed

    private void btnLimpiarmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarmateriaActionPerformed
        if (TxThora.getText().length() > 0) {
            TxThora.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (txtDiaHorario.getText().length() > 0) {
            txtDiaHorario.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (txtNombreDelDocente.getText().length() > 0) {
            txtNombreDelDocente.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (txtNombreMateria.getText().length() > 0) {
            txtNombreMateria.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
    }//GEN-LAST:event_btnLimpiarmateriaActionPerformed

    private void btnSalirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMateriaActionPerformed

        new PrincipalView(controlador).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMateriaActionPerformed

    private void btnGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaActionPerformed
        String nombreMateria = txtNombreMateria.getText();
        String docente = txtNombreDelDocente.getText();
        String dia = txtDiaHorario.getText();
        String hora=TxThora.getText();
        
         if (nombreMateria.isEmpty() || docente.isEmpty() || dia.isEmpty()|| hora.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor complete todos los campos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //  Crear la nueva meta
        Materia nuevaMateria = new Materia(
                nombreMateria,
                docente , 
                dia,
                hora
                
        );

        // Guardar en el controlador
        controlador.agregarMateria(nuevaMateria);

        //  Mostrar confirmación
        JOptionPane.showMessageDialog(this,
                "Materia guardada exitosamente!",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
                                  
    }//GEN-LAST:event_btnGuardarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxThora;
    private javax.swing.JButton btnGuardarMateria;
    private javax.swing.JButton btnLimpiarmateria;
    private javax.swing.JButton btnSalirMateria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtDiaHorario;
    private javax.swing.JTextField txtNombreDelDocente;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables

}
