package ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Vista;

import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Controlador.AgendaController;
import javax.swing.JOptionPane;

/**
 *
 * @author and_j
 */
public class NewJframe extends javax.swing.JFrame {

    /**
     * Creates new form NewJframe
     */
     private AgendaController controlador;
    public NewJframe(AgendaController controlador) {
        this.controlador =controlador;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        IngresaTarea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIngresaDescripcion = new javax.swing.JTextField();
        txtIngresaFecha = new javax.swing.JTextField();
        btnCompetadoSiTareas = new javax.swing.JRadioButton();
        btnCompetadoNoTareas = new javax.swing.JRadioButton();
        btnGuardarTarea = new javax.swing.JButton();
        btnSalirTarea = new javax.swing.JButton();
        btnLimpiarTarea = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoraTareas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("MiVidaEspoch");

        IngresaTarea.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        IngresaTarea.setText("Ingreso de Tareas");

        jLabel2.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Fecha entrega");

        jLabel4.setText("Completado");

        txtIngresaDescripcion.setText("ejem,Trabajo Biblioteca");
        txtIngresaDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresaDescripcionActionPerformed(evt);
            }
        });

        txtIngresaFecha.setText("ejem, martes");
        txtIngresaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresaFechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnCompetadoSiTareas);
        btnCompetadoSiTareas.setText("Si");

        buttonGroup1.add(btnCompetadoNoTareas);
        btnCompetadoNoTareas.setText("No");

        btnGuardarTarea.setText("Guardar");
        btnGuardarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTareaActionPerformed(evt);
            }
        });

        btnSalirTarea.setText("Salir");
        btnSalirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTareaActionPerformed(evt);
            }
        });

        btnLimpiarTarea.setText("Limpiar");
        btnLimpiarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTareaActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora:");

        jLabel6.setText("Dia:");

        txtHoraTareas.setText("ejem, media noche");
        txtHoraTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraTareasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IngresaTarea)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIngresaFecha)
                                    .addComponent(txtHoraTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtIngresaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCompetadoSiTareas)
                                .addGap(34, 34, 34)
                                .addComponent(btnCompetadoNoTareas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardarTarea)
                                    .addComponent(btnLimpiarTarea)
                                    .addComponent(btnSalirTarea))
                                .addGap(22, 22, 22))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(IngresaTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngresaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIngresaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnLimpiarTarea)
                                .addGap(5, 5, 5)
                                .addComponent(btnGuardarTarea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalirTarea)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(btnCompetadoSiTareas)
                                    .addComponent(btnCompetadoNoTareas))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHoraTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresaDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresaDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresaDescripcionActionPerformed

    private void btnGuardarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarTareaActionPerformed

    private void btnSalirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTareaActionPerformed
        new PrincipalView(controlador).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirTareaActionPerformed

    private void txtIngresaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresaFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresaFechaActionPerformed

    private void txtHoraTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraTareasActionPerformed

    private void btnLimpiarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTareaActionPerformed
       //estos condicionales sirven para el boton limpiar, si lo limpian y no estan llenos dice que lleno los campos
        if (txtIngresaDescripcion.getText().length() > 0) {

            txtIngresaDescripcion.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (txtHoraTareas.getText().length() > 0) {
            txtHoraTareas.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (txtIngresaFecha.getText().length() > 0) {
            txtIngresaFecha.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (btnCompetadoNoTareas.getText().length() > 0) {
            btnCompetadoNoTareas.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
        if (btnCompetadoSiTareas.getText().length() > 0) {
            btnCompetadoSiTareas.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se puede limpiar,llene los campos");
        }
    }//GEN-LAST:event_btnLimpiarTareaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IngresaTarea;
    private javax.swing.JRadioButton btnCompetadoNoTareas;
    private javax.swing.JRadioButton btnCompetadoSiTareas;
    private javax.swing.JButton btnGuardarTarea;
    private javax.swing.JButton btnLimpiarTarea;
    private javax.swing.JButton btnSalirTarea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtHoraTareas;
    private javax.swing.JTextField txtIngresaDescripcion;
    private javax.swing.JTextField txtIngresaFecha;
    // End of variables declaration//GEN-END:variables

}
