package ec.gob.orellana.www.agendaestudiantilespoch.Vista;
import ec.gob.orellana.www.agendaestudiantilespoch.Controlador.ControladorInterfaces;
import ec.gob.orellana.www.agendaestudiantilespoch.Modelo.Cola;

/**
 *
 * @author and_j
 */
public class PrincipalView extends javax.swing.JFrame {

    private ControladorInterfaces controladorInterfaces;

    public PrincipalView() {
        initComponents();

        this.controladorInterfaces = new ControladorInterfaces();
        
        //centrar la ventana
        this.setLocationRelativeTo(null);
         this.controladorInterfaces.setCola(Cola.getInstancia()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        btnTareas = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnMetas = new javax.swing.JButton();
        btnResgistrado = new javax.swing.JButton();
        btnExamen = new javax.swing.JButton();

        jFrame1.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("MiVidaEspoch");

        btnTareas.setText("Tareas");
        btnTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasActionPerformed(evt);
            }
        });

        btnMaterias.setText("Materias");
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });

        btnMetas.setText("Metas");
        btnMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetasActionPerformed(evt);
            }
        });

        btnResgistrado.setText("Registrado");
        btnResgistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResgistradoActionPerformed(evt);
            }
        });

        btnExamen.setText("Examen");
        btnExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnTareas)
                        .addGap(30, 30, 30)
                        .addComponent(btnMaterias)
                        .addGap(28, 28, 28)
                        .addComponent(btnExamen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnMetas)
                        .addGap(31, 31, 31)
                        .addComponent(btnResgistrado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaterias)
                    .addComponent(btnTareas)
                    .addComponent(btnExamen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetas)
                    .addComponent(btnResgistrado))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasActionPerformed
        //new NewJframe(controlador).setVisible(true);
        controladorInterfaces.procesoNavegar("tarea");

    }//GEN-LAST:event_btnTareasActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        controladorInterfaces.procesoNavegar("materia");
        //conecta la interfaz con boton 
        // new NewJFrameMaterias(controlador).setVisible(true);
        //sirve para que no se abra todas las pestañas y solo se mantenga una
        // this.dispose();
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetasActionPerformed
        controladorInterfaces.procesoNavegar("meta");
        //new NewJFrameMetas(controlador).setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnMetasActionPerformed

    private void btnExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamenActionPerformed
        controladorInterfaces.procesoNavegar("examen");
        //new NewJFrameExamen(controlador).setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnExamenActionPerformed

    private void btnResgistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResgistradoActionPerformed
        //new NewJFramefinal(controlador).setVisible(true);
       // this.dispose();
    }//GEN-LAST:event_btnResgistradoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExamen;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnMetas;
    private javax.swing.JButton btnResgistrado;
    private javax.swing.JButton btnTareas;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
